management:
    endpoints:
        web:
            exposure:
                include: "*"

cds:
  sql.hana.search:
    fuzzy: true
    fuzzinessThreshold: 0.9
  security.mock.users:
    martha:
      roles: [ reviewer ]
    bob:
      roles: [ support ]
    amy:
      roles: [ processor ]
    admin:
      roles: [ admin ]
      password: admin
  remote:
    services:
      PassengerService:
        destination:
          name: PassengerService
          properties:
            url: http://localhost:4005
            username: internal
            authentication: BasicAuthentication
            password:
        name: PassengerService
        type: odata-v4
        http:
          suffix: odata/v4
          service: 
  odata-v4:
    endpoint:
      path: "/"

---
spring:
    config.activate.on-profile: default

server:
    port: 4004

---
spring:
    config.activate.on-profile: cloud
    sql.init.mode: never

cds:
    datasource:
        csv.initialization-mode: never
